# Compose file for development builds
#
# Be sure to set environment variable in .env
#
# To build and run:
#    docker-compose up -f docker-compose-dev.yml

version: "3"

services:

  neo4j:
    env_file: .env
    image: neo4j
    ports:
      - "7474:7474"
      - "7687:7687" 
    expose:
      - "7687"
    environment:
      - NEO4J_AUTH=none
    volumes:
      - "neo4j:/var/lib/neo4j/data"

  mongo:
    image: mongo
    expose:
      - "27017"
    volumes:
      - "data:/data/db"

  node_webapp:
    env_file: .env
    build:
      context: ./
      dockerfile: ./Dockerfile.app
    ports:
      - "${PORT}:80"

  loc_data_miner:
    env_file: .env
    build: 
      context: ./
      dockerfile: ./Dockerfile.loc
    volumes:
      - "loc:/usr/src/loc"
  
  worldcat_data_miner:
    env_file: .env
    build: 
      context: ./
      dockerfile: ./Dockerfile.worldcat

volumes:
  data:
  neo4j:
  loc:
